# Generated by Django 3.1.7 on 2021-04-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('note', models.TextField()),
                ('type', models.CharField(choices=[('INCOME', 'รายรับ'), ('EXPENSE', 'รายจ่าย')], max_length=32)),
            ],
        ),
    ]
